[build]
  functions = "functions"  # Folder where your functions are located


[[plugins]]
  package = "@netlify/plugin-functions-install-core"  # Ensures necessary dependencies for functions are installed

[functions]
directory = "functions"

[build]
  command = "pip install -r requirements.txt"





[dev]
  command = "gunicorn wsgi:app" 

